### ISSUE TITLE
SJ1

### ISSUE THREAD

**Issue by raspberry007** [hallard/Lora-Breakout#1]
Hi,

Would you please help to understand the SJ1? It contains the following:
- SDA
- CE
- LED

How do I wire it please? Do I hook up SDA or CE to LED?

Thanks
Alex

**Comment by hallard** [comment]
@alex1sh 
SJ1 is just for some feature, you don't need it for Lora, but if you connect 
If you want to map CE to LED just put solder between CE and LED of SJ1
If you want to use ATSHA then, just put solder between CE and SDA of SJ1, the CE pin is used as SDA to drive ATSHA chip, but in this case you'll need to write the code to use this chip.

**Comment by raspberry007** [comment]
@hallard - many thanks. Can I drive both LED and ATSHA with CE, i.e. solder all three pads of SJ1?
Yes, the code (MySensors) does handle ATSHA204A

**Comment by hallard** [comment]
It should, but you need to try, and talking to ATSHA will override led state ;-)
